version: 0.2

phases:
  pre_build:
    commands:
      - cd client
      - npm install --no -optional

  build:
    commands:
      - cd client
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build